### ISSUE TITLE
auto-complete menu

### ISSUE THREAD

**Issue by rcrooks** [brittneypostma/deep-water#5]
Hi again @brittneypostma  - those are some nice new variants you added in the most recent release (though I still like the original best :) )

One other minor issue: the selected item in the autocomplete menu needs a different font or background color - it's fully or partly hidden by absence of contrast. I'm attaching a screenshot to illustrate.

Best,
Robert
<img width="679" alt="2020-08-20_14-33-16" src="https://user-images.githubusercontent.com/619617/90811540-c8613c00-e2f2-11ea-91f0-176400fecd16.png">

**Comment by brittneypostma** [comment]
Thank you again! I will take care of it tonight!

**Comment by brittneypostma** [comment]
Just pushed a change, should be fixed.

**Comment by rcrooks** [comment]
That is **much** better! There is still a small issue though when the autocomplete menu pops up in the middle of typing a word - the part you have typed and part of the top selection are still obscured.
<img width="557" alt="2020-08-21_08-27-54" src="https://user-images.githubusercontent.com/619617/90890790-a87c5780-e388-11ea-8fff-ec16fcbdc6fc.png">

**Comment by brittneypostma** [comment]
I just sent another change that should fix that. Please continue to reach out if you see more issues! Love your font btw, what is that?

**Comment by rcrooks** [comment]
Thanks!

The font is called monofur. Can't remember where I originally found it, but always liked it. Someone added italics a year or two ago which was nice. Only thing is that they are technically two separate fonts, so to get it to work in apps like VSCode, you have to specify both: monofur, 'monofur italic'. I can dig up the links for them if you want, but they're pretty easy to find on the web.

**Comment by brittneypostma** [comment]
I'm sure I can find it. Thank you again!
