### ISSUE TITLE
Not sure if this is a suggestion or a fix

### ISSUE THREAD

**Issue by rcrooks** [brittneypostma/deep-water#6]
HI again @brittneypostma - I was going to enter this as a suggestion, but then looking again at the HTML sample screenshot in your readme, I think maybe what's there currently wasn't what you intended. In the sample, plain text looks significantly lighter than the tag name color, which I think enhances the code readability. In the current build, though, they are nearly the same color (screenshot attached).

Anyway, I'll just enter this as a suggestion, and defer to your far greater design skills and sensibility.

<img width="777" alt="2020-08-24_09-26-40" src="https://user-images.githubusercontent.com/619617/91050398-969aee80-e5ec-11ea-92d1-250923ce2776.png">

**Comment by brittneypostma** [comment]
You may be correct, I changed a lot of colors looking for the right one for the highlight, I will check and see where that went wrong!

**Comment by brittneypostma** [comment]
I just pushed a change for this, turns out it was simple, thanks for pointing it out. Please continue to offer updates/suggestions! Thank you!

**Comment by rcrooks** [comment]
Did you actually update the package on the VSC marketplace? didn't see it - but no hurry, was just checking.

**Comment by brittneypostma** [comment]
Hmm, thought I did, but I will try again.

**Comment by brittneypostma** [comment]
I just pushed it again, I was on my laptop last time, something could have went wrong. Let me know if that doesn't work either.

**Comment by rcrooks** [comment]
There now, and the change is great!

**Comment by brittneypostma** [comment]
Perfect!
